console.log('products.js loaded');
window.products = [
  {
    id: 1,
    name: "Men's cabretta golf glove",
    price: 19.0,
    image: "/assets/fimage1.jpg",
    rating: 5,
    hot: true,
    discount: null,
  },
  {
    id: 2,
    name: "Greg Norman - Men's Shirt",
    price: 24.99,
    originalPrice: 40.0,
    image: "/assets/fimage2.jpg",
    rating: 5,
    hot: true,
    discount: 50,
  },
  {
    id: 3,
    name: "G/FORE - Mens 2023",
    price: 30.0,
    image: "/assets/fimage3.jpg",
    rating: 5,
    hot: true,
    discount: null,
  },
  {
    id: 4,
    name: "Utility Rover-R Double - 2023",
    price: 209.99,
    image: "/assets/fimage4.jpg",
    rating: 5,
    hot: true,
    discount: null,
  },
  {
    id: 5,
    name: "Air Jordan 1 - SS23",
    price: 111.99,
    originalPrice: 200.0,
    image: "/assets/fimage5.jpg",
    rating: 5,
    hot: true,
    discount: 50,
  },
  {
    id: 6,
    name: "Air Jordan 1 - SS23",
    price: 111.99,
    originalPrice: 200.0,
    image: "/assets/fimage6.jpg",
    rating: 5,
    hot: true,
    discount: 50,
  },
  {
    id: 7,
    name: "Air Jordan 1 - SS23",
    price: 111.99,
    originalPrice: 200.0,
    image: "/assets/fimage7.jpg",
    rating: 5,
    hot: true,
    discount: 50,
  },
];